/*CREACIÓN DE LA BASE DE DATOS 'PAIS' */

drop database if exists PAIS;

create database PEDIDOS;

/*CREACIÓN DE LA TABLA PROVINCIA */

CREATE TABLE PROVINCIA (
	CODPROV CHAR(2) PRIMARY KEY,
    NOMBRE_PROVINCIA VARCHAR(30)
);

/*INTRODUZCO PROVINCIAS */

INSERT INTO PROVINCIA VALUES ('01', 'Araba/Álava');
INSERT INTO PROVINCIA VALUES ('02', 'Albacete');
INSERT INTO PROVINCIA VALUES ('03', 'Alacant/Alicante');
INSERT INTO PROVINCIA VALUES ('04', 'Almería');
INSERT INTO PROVINCIA VALUES ('05', 'Ávila');
INSERT INTO PROVINCIA VALUES ('06', 'Badajoz');
INSERT INTO PROVINCIA VALUES ('07', 'Illes Balears');
INSERT INTO PROVINCIA VALUES ('08', 'Barcelona');
INSERT INTO PROVINCIA VALUES ('09', 'Burgos');
INSERT INTO PROVINCIA VALUES ('10', 'Cáceres');
INSERT INTO PROVINCIA VALUES ('11', 'Cádiz');
INSERT INTO PROVINCIA VALUES ('12', 'Castelló/Castellón');
INSERT INTO PROVINCIA VALUES ('13', 'Ciudad Real');
INSERT INTO PROVINCIA VALUES ('14', 'Córdoba');
INSERT INTO PROVINCIA VALUES ('15', 'A Coruña');
INSERT INTO PROVINCIA VALUES ('16', 'Cuenca');
INSERT INTO PROVINCIA VALUES ('17', 'Girona');
INSERT INTO PROVINCIA VALUES ('18', 'Granada');
INSERT INTO PROVINCIA VALUES ('19', 'Guadalajara');
INSERT INTO PROVINCIA VALUES ('20', 'Gipuzkoa');
INSERT INTO PROVINCIA VALUES ('21', 'Huelva');
INSERT INTO PROVINCIA VALUES ('22', 'Huesca');
INSERT INTO PROVINCIA VALUES ('23', 'Jaén');
INSERT INTO PROVINCIA VALUES ('24', 'León');
INSERT INTO PROVINCIA VALUES ('25', 'Lleida');
INSERT INTO PROVINCIA VALUES ('26', 'La Rioja');
INSERT INTO PROVINCIA VALUES ('27', 'Lugo');
INSERT INTO PROVINCIA VALUES ('28', 'Madrid');
INSERT INTO PROVINCIA VALUES ('29', 'Málaga');
INSERT INTO PROVINCIA VALUES ('30', 'Murcia');
INSERT INTO PROVINCIA VALUES ('31', 'Navarra');
INSERT INTO PROVINCIA VALUES ('32', 'Ourense');
INSERT INTO PROVINCIA VALUES ('33', 'Asturias');
INSERT INTO PROVINCIA VALUES ('34', 'Palencia');
INSERT INTO PROVINCIA VALUES ('35', 'Las Palmas');
INSERT INTO PROVINCIA VALUES ('36', 'Pontevedra');
INSERT INTO PROVINCIA VALUES ('37', 'Salamanca');
INSERT INTO PROVINCIA VALUES ('38', 'Santa Cruz de Tenerife');
INSERT INTO PROVINCIA VALUES ('39', 'Cantabria');
INSERT INTO PROVINCIA VALUES ('40', 'Segovia');
INSERT INTO PROVINCIA VALUES ('41', 'Sevilla');
INSERT INTO PROVINCIA VALUES ('42', 'Soria');
INSERT INTO PROVINCIA VALUES ('43', 'Tarragona');
INSERT INTO PROVINCIA VALUES ('44', 'Teruel');
INSERT INTO PROVINCIA VALUES ('45', 'Toledo');
INSERT INTO PROVINCIA VALUES ('46', 'València/Valencia');
INSERT INTO PROVINCIA VALUES ('47', 'Valladolid');
INSERT INTO PROVINCIA VALUES ('48', 'Bizkaia');
INSERT INTO PROVINCIA VALUES ('49', 'Zamora');
INSERT INTO PROVINCIA VALUES ('50', 'Zaragoza');
INSERT INTO PROVINCIA VALUES ('51', 'Ceuta');
INSERT INTO PROVINCIA VALUES ('52', 'Melilla');

/*CREACIÓN DE UN PROCEDIMIENTO QUE CREA ENCUESTAS FICTICIAS */

CREATE OR REPLACE PROCEDURE enc_fic() AS
$body$

DECLARE

CONT INT;
CONTAD INT;
CODIGO CHAR(2);
SON INT;
IMG INT;
USA INT;


BEGIN

CREATE TABLE ENCUESTA (
IDENCUESTA serial PRIMARY KEY ,
CODPROV CHAR(2),
   FOREIGN KEY (CODPROV) REFERENCES PROVINCIA(CODPROV),
   SONIDO integer NOT NULL,
IMAGEN integer NOT NULL,
USABILIDAD integer NOT NULL
);
CONT:=1;

WHILE (CONT<52) LOOP

    CODIGO := LPAD(CONT::text, 2, '0');
CONT:= CONT + 1;
    CONTAD:=0;

WHILE (CONTAD<10) LOOP
    CONTAD := CONTAD + 1;
    SON := FLOOR(RANDOM()*(11));
IMG := FLOOR(RANDOM()*(11));
USA := FLOOR(RANDOM()*(11));
INSERT INTO ENCUESTA (CODPROV, SONIDO, IMAGEN, USABILIDAD) VALUES (CODIGO, SON, IMG, USA);
END LOOP;
END LOOP;


END
$body$
LANGUAGE plpgsql;

/*LLAMAMOS AL PROCEDIMIENTO */

call enc_fic();



/*SENTENCIAS SELECT */

SELECT IDENCUESTA, CODPROV, SONIDO, IMAGEN, USABILIDAD, (SONIDO+IMAGEN+USABILIDAD)/3 AS MEDIA
FROM encuesta;



SELECT ENCUESTA.IDENCUESTA, PROVINCIA.NOMBRE_PROVINCIA, ENCUESTA.CODPROV, ENCUESTA.SONIDO, ENCUESTA.IMAGEN, ENCUESTA.USABILIDAD,
(SONIDO+IMAGEN+USABILIDAD)/3 AS MEDIA
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV



SELECT ENCUESTA.CODPROV, PROVINCIA.NOMBRE_PROVINCIA,
round(AVG(ENCUESTA.SONIDO), 2) AS MEDIA_SONIDO,
round(AVG(ENCUESTA.IMAGEN),2) AS MEDIA_IMAGEN,
round(AVG(ENCUESTA.USABILIDAD),2) AS MEDIA_USABILIDAD
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV
GROUP BY encuesta.CODPROV, provincia.nombre_provincia;



SELECT ENCUESTA.CODPROV, PROVINCIA.NOMBRE_PROVINCIA,
round(AVG(ENCUESTA.SONIDO), 2) AS MEDIA_SONIDO,
round(AVG(ENCUESTA.IMAGEN),2) AS MEDIA_IMAGEN,
round(AVG(ENCUESTA.USABILIDAD),2) AS MEDIA_USABILIDAD
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV
GROUP BY encuesta.CODPROV, provincia.nombre_provincia;



SELECT ENCUESTA.CODPROV, PROVINCIA.NOMBRE_PROVINCIA,
round(AVG(ENCUESTA.SONIDO), 2) AS MEDIA_SONIDO,
round(AVG(ENCUESTA.IMAGEN),2) AS MEDIA_IMAGEN,
round(AVG(ENCUESTA.USABILIDAD),2) AS MEDIA_USABILIDAD,
round((AVG(ENCUESTA.SONIDO)+AVG(ENCUESTA.IMAGEN)+AVG(ENCUESTA.USABILIDAD))/3, 2) AS MEDIA
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV
GROUP BY encuesta.CODPROV, provincia.nombre_provincia;



SELECT ENCUESTA.CODPROV, PROVINCIA.NOMBRE_PROVINCIA,
round(AVG(ENCUESTA.SONIDO), 2) AS MEDIA_SONIDO,
round(AVG(ENCUESTA.IMAGEN),2) AS MEDIA_IMAGEN,
round(AVG(ENCUESTA.USABILIDAD),2) AS MEDIA_USABILIDAD,
round((AVG(ENCUESTA.SONIDO)+AVG(ENCUESTA.IMAGEN)+AVG(ENCUESTA.USABILIDAD))/3, 2) AS MEDIA
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV
GROUP BY encuesta.CODPROV, provincia.nombre_provincia
HAVING (AVG(ENCUESTA.SONIDO)+AVG(ENCUESTA.IMAGEN)+AVG(ENCUESTA.USABILIDAD))/3 <=6



SELECT ENCUESTA.CODPROV, PROVINCIA.NOMBRE_PROVINCIA,
round(AVG(ENCUESTA.SONIDO), 2) AS MEDIA_SONIDO,
round(AVG(ENCUESTA.IMAGEN),2) AS MEDIA_IMAGEN,
round(AVG(ENCUESTA.USABILIDAD),2) AS MEDIA_USABILIDAD,
round((AVG(ENCUESTA.SONIDO)+AVG(ENCUESTA.IMAGEN)+AVG(ENCUESTA.USABILIDAD))/3, 2) AS MEDIA
FROM encuesta
INNER JOIN PROVINCIA
ON ENCUESTA.CODPROV=PROVINCIA.CODPROV
GROUP BY encuesta.CODPROV, provincia.nombre_provincia
ORDER BY MEDIA DESC LIMIT 1;



/*CREACIÓN DE FUNCION QUE MUESTRA QUE VALORACION GANA */

CREATE OR REPLACE FUNCTION valoracion(s int,i int, u int)
RETURNS char(20) AS
$body$
BEGIN

IF S>I AND S>U THEN
RETURN 'Gana Sonido';
ELSEIF I>S AND I>U THEN
RETURN 'Gana Imagen';
ELSEIF U>S AND U>I THEN
RETURN 'Gana Usabilidad';
ELSEIF S=I THEN
RETURN 'Empate, gana Sonido';
ELSEIF S=U THEN
RETURN 'Empate, gana Sonido';
ELSE
RETURN 'Empate, gana Imagen';
END IF;

END
$body$
LANGUAGE plpgsql;

/*PROBAMOS LA FUNCION */

select IDENCUESTA, CODPROV, SONIDO, IMAGEN, USABILIDAD, VALORACION(SONIDO, IMAGEN, USABILIDAD) FROM ENCUESTA
